package sn.pad.pe.pss.bo;
// Generated 11 oct. 2018 10:10:58 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "parametre", schema = "public")
public class Parametres implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idparametre;
	private String code;
	private String libelleparametre;
	private int valeur;

	public Parametres() {
	}

	public Parametres(int idparametre, String code, String libelleparametre, int valeur) {
		this.idparametre = idparametre;
		this.code = code;
		this.libelleparametre = libelleparametre;
		this.valeur = valeur;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "idparametre", unique = true, nullable = false)

	public int getIdparametre() {
		return idparametre;
	}

	public void setIdparametre(int idparametre) {
		this.idparametre = idparametre;
	}

	@Column(name = "code", length = 254)
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelleparametre", length = 254)
	public String getLibelleparametre() {
		return libelleparametre;
	}

	public void setLibelleparametre(String libelleparametre) {
		this.libelleparametre = libelleparametre;
	}

	@Column(name = "valeur")
	public int getValeur() {
		return valeur;
	}

	public void setValeur(int valeur) {
		this.valeur = valeur;
	}
}
