
package sn.pad.pe.pss.bo;
// Generated 10 juil. 2019 15:46:52 by Hibernate Tools 5.2.10.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Role generated by hbm2java
 */
@Entity
public class Ressource implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	private String name;
	@Column(unique = true)
	private String nomRessource;

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "ressource")
	private List<Privilege> privileges;

	public Ressource() {
		super();
	}

	public Ressource(String name) {
		super();
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNomRessource() {
		return nomRessource;
	}

	public void setNomRessource(String nomRessource) {
		this.nomRessource = nomRessource;
	}

	public List<Privilege> getPrivileges() {
		return privileges;
	}

	public void setPrivileges(List<Privilege> privileges) {
		this.privileges = privileges;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((nomRessource == null) ? 0 : nomRessource.hashCode());
		result = prime * result + ((privileges == null) ? 0 : privileges.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Ressource other = (Ressource) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (nomRessource == null) {
			if (other.nomRessource != null)
				return false;
		} else if (!nomRessource.equals(other.nomRessource))
			return false;
		if (privileges == null) {
			if (other.privileges != null)
				return false;
		} else if (!privileges.equals(other.privileges))
			return false;
		return true;
	}

}
